- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: install packages base packages
    apt:
      name:
        - sudo
        - vim
        - curl
        - wget
        - git-all
        - build-essential
        - software-properties-common
        - glances
        - net-tools
        - glances
        - unzip
        - tar
        - ntp
      state: latest
      update_cache: true
    tags: packages
  - debug:
      msg:
        - System asdasdasd